kind: Gateway
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: control-gateway
  namespace: istio-system
  labels:
    module: m3
spec:
  servers:
    - hosts:
        - istio-ingressgateway-istio-system.apps.cluster-zkp45.dynamic.redhatworkshops.io
      port:
        name: http
        number: 80
        protocol: HTTP
  selector:
    istio: ingressgateway

---
kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: control
  namespace: travel-control
  labels:
    module: m3
spec:
  hosts:
    - istio-ingressgateway-istio-system.apps.cluster-zkp45.dynamic.redhatworkshops.io
  gateways:
    - istio-system/control-gateway
  http:
    - route:
        - destination:
            host: control.travel-control.svc.cluster.local
            subset: v1
          weight: 100
          
---
kind: DestinationRule
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: control
  namespace: travel-control
  labels:
    module: m3  
spec:
  host: control.travel-control.svc.cluster.local
  subsets:
    - labels:
        version: v1
      name: v1
