apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  name: travel-control-local
  namespace: openshift-gitops
spec:
  project: travel
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  ignoreDifferences:
    - group: argoproj.io
      jsonPointers:
        - /status
      kind: Application
    - group: triggers.tekton.dev
      jsonPointers:
        - /status
      kind: EventListener
    - group: triggers.tekton.dev
      jsonPointers:
        - /status
      kind: TriggerTemplate
    - group: triggers.tekton.dev
      jsonPointers:
        - /status
      kind: TriggerBinding
    - group: route.openshift.io
      jsonPointers:
        - /spec/host
      kind: Route
  source:
    path: deployment/travel-control
    targetRevision: main
    repoURL: https://github.com/marrober/summit-connect-2025.git
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true 
      allowEmpty: false 
    syncOptions: 
      - Validate=true 
      - CreateNamespace=false 
      - PrunePropagationPolicy=foreground 
      - PruneLast=true 
    retry:
      limit: 1 
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 20s 