apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: podmonitors-rbac
  namespace: travel-control
rules:
  - apiGroups:
      - 'monitoring.coreos.com'
    resources:
      - podmonitors
    verbs:
      - get
      - watch
      - list
      - create
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: podmonitors-admin
  namespace: travel-control
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: podmonitors-rbac
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: argocd-admin
  namespace: travel-control
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops