apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: pipelines-binding
placementRef:
  name: openshift-clusters-pipelines
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: pipelines-operator
  kind: Policy
  apiGroup: policy.open-cluster-management.io
